server:
  port: 6000
spring:
  application:
    name: atguigu-crowd-order
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  redis:
    host: 127.0.0.1
  session:
    store-type: redis
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka

ali:
  pay:
    appId: 2021000117614123
    merchantPrivateKey: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCOI/B7QbCQ9mVR4zsHVb2qXPD7St0CkHZtBqt7hLNd2f59gvlwN1XQeXGeCTn+9wVbbhO1rlGx0QSdb/CZ39hENZ/taF+Vej4GPia2SfT8OtAD1vDTwFv47W1obBTV/u3wtA9KfnfulUpHq0gVRvjhfPErrhea9YeYVVeHRgtVHYaVHkGLGReyE7cwNv3AKnsYsJR9vv9h7gUyEZ0oPo1PIoItXmLxIWk236IGpFFirAEQvDixiV/+M/Lu+xmHhS2WaQEWjlJHjEzumDKq+QJQJv0dYWSn+OgXzHa78hwD9NWsrA+hRfqBX4BNIylc4q7NzeevSxGeHSvdtCmi83d7AgMBAAECggEAaJCf1Mzaa4oXt0oGnrrAsJd24CaOt9g2hrYlaNSSbzRzNzom7hqHErqEjtISzDJEyqIL9derWbh+QKOcyFYX7vXUFP53cqte/ZCzQd7eTr+lT23L9LrJ7jIcDnmUSmkj+bM8nHy1FdrVriue96giZx9W+98ylliRy8rcfTNWGuJk9A76vtarCOSBThgThmogmcGLas+uVqCDvfquuFynRgc4MzkPFwpEA0eMFOQIKUPBTQu8PIu7eNBAcXfWFvN0wJdCaNUjnK+vZYaJFIDCJ9cVJd+vCtXpnt7ihJvbwxmomPapEVnTehgQv6b1ZWryNMn+eB20fgmBnYD+87kdAQKBgQDh5oTNMM8mBQ0bG5DfFgDcpx1Iug+voAuITxhfSTL+r7kxgR9U0nc5eM8Puse/k2Lg0r9hpeVXowfVMPIlw5XThLIxYIE/q4FXdbyBY2v7AqAf1Iqi7277A1GSLbQ9FEaX352qB2h8YC/NnTwP33aubpnkBCSGiitIz2ytg4FxoQKBgQChFFu9IYIR9ljb0/IrgFq63N22iJnq0Jwb1Hmx0qpzsq8C7FcrxQbcDO3u5fmZMbXGE3tbaKCnzGFmRCPNIxnf+/GLQXLOwsQlVu2rJXkSC/8Nug/4nJUd7T96fPYZu5gBVuIqV7svvCb+9bKGs5oivSUAfh8w8FDJd6fo7dnLmwKBgDFs4VOPwVL9Oe/baSgWRVwByFt4MiRn7P4G6Ds45cppoihdqwBBCErvzsYPRNL6qWCtW6g+xt4U0ornqaNvlqFv4BkDl2PZ33PGU9cvbJm/6k7sjuS1ZF/RSxCjpVLT09o41+Myub60wODI7TI/31Ss6EjGS0OQiYXltE6GflThAoGANVFk0GTQBhwR66nrRiT1Y1cKeIoc0JH+qmOZaJf/3c4uifwrGozcKWiKNYKgLOo8bfUy5t3qF8DaGJzDcPqGbRKbMGoYk4H6pRVyFC2SNrwLz8Jf2P4TidVnJqdIWtoyhXb54+QoTLOuAMTZNCctBQSww8n7jxps01MtHDfm2LMCgYEAtDSrA5dTwDJXglBqNu2/izCfA8nl546/6ruabJoytpvvhKmOEAKss1I6etbS8sxujleJPWkzyYtDNQpN1VlFA/bj/ZajlpoJxbipxsej4SXFxaiZOsZur47rPJMh2/SmR0M/R8mANzTBR465wJD6x0Q8iHgwrLAynTVStlSGYuM=
    alipayPublicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAks0wwRk9dSp5BQUGSYShsMYuKdC3lO696p73Y6gCxkd400VBbPrORlQYp1RGmvxxXUlqIBNeBxgTaVyNAy3EGvFwS8/NNRdFyqXOb8997dNNd0jr2iiJZrHbMyJde2pyGwSQn+sBQF0WEVv3jPVSpVb9wqSpillu4EDNzQusJ5an0jFyjoQB/EJtFypDD62qzf2jZCX/btsuKlASRnDs2sSGFPLF0Njl2PMczTmAYQu2sAdCsZXde48LbksQ6WB7iSC8nVyoJWjKlh1dvfHC9QNDCbvi3XSk6kLrRwo46rjWjqVCgjLhjfJvzr6M624U7ZDMaSofGKtsBhYsiXX+kQIDAQAB
    notifyUrl: http://47.108.167.132/order/notify
    returnUrl: http://47.108.167.132/order/return
    signType: RSA2
    charset: utf-8
    gatewayUrl: https://openapi.alipaydev.com/gateway.do

