server:
  port: 80
spring:
  application:
    name: atguigu-crowd-zuul
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka
zuul:
  ignored-services: "*"  #忽略原本的微服务名字
  sensitive-headers: "*" #在Zuul项其他微服务重定向时保持原本头信息
  routes: #自定义路由规则
    crowd-potal: #自定义路由规则名称
      service-id: atguigu-crowd-auth #针对的微服务路由设置
      path: /** #通过 /** 访问potal-view微服务，当网址请求通过 80端口发送任何请求，都被重定向给 atguigu-crowd-auth微服务